---
title: "miaTime: Microbiome Time Series Analysis"
date: "`r Sys.Date()`"
author:
- name: Leo Lahti
  email: leo.lahti@iki.fi
- name: Yagmur Simsek
  email: yagmur.simsek@hsrw.org
package: 
    miaTime
output: 
    BiocStyle::html_document:
        fig_height: 7
        fig_width: 10
        toc: yes
        toc_depth: 2
        number_sections: true
vignette: >
    %\VignetteIndexEntry{miaTime}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---

```{r eval=FALSE, include=FALSE}
library(Cairo)
knitr::opts_chunk$set(cache = FALSE,
                      fig.width = 9,
                      dpi=300,
                      dev = "png",
                      dev.args = list(type = "cairo-png"),
                      message = FALSE,
                      warning = FALSE)
```




# Introduction

`miaTime` implements tools for time series manipulation based on the `TreeSummarizedExperiment` data container.

## Installation

Installing the latest development version in R.

```{r, eval=FALSE}
library(devtools)
devtools::install_github("microbiome/miaTime")
```

Loading the package:

```{r load-packages, message=FALSE, warning=FALSE}
library(miaTime)
```


See [articles](https://microbiome.github.io/miaTime/articles/) for more detailed example workflows.


## Session info

```{r}
sessionInfo()
```
